version: "3.7"

networks:
  postgres:
    external: true
    name: postgres
  reverse-proxy:
    external: true
    name: reverse-proxy

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      # - ./volumes/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - NEXTCLOUD_DB_PASSWORD