version: "3.7"

networks:
  redis:
    external: true
    name: redis

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./volumes/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - redis